apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: docker.io/boiyeove/udagram-api-feed:v7
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
          - configMapRef:
              name: env-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend-feed
  labels:
    run: backend-feed
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: backend-feed