apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: reverseproxy


kubectl apply -f backend_user_deployment.yaml
kubectl apply -f frontend_deployment.yaml
kubectl apply -f reverseproxy_deployment.yaml
kubectl apply -f backend_user_service.yaml
kubectl apply -f frontend_service.yaml
kubectl apply -f reverseproxy_service.yaml

kubectl expose deployment reverseproxy --type=LoadBalancer --name=publicreverseproxy
    